name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repositorio
        uses: actions/checkout@v3

      - name: Preparamos Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalamos dependencias
        run: npm install

      - name : Elevamos permisos de Lint
        run: chmod +x ./node_modules/.bin/eslint

      - name: Elevamos permisos de Jest
        run: chmod +x ./node_modules/.bin/jest

      - name: Auditoría de seguridad
        run: npm audit --audit-level=high

      - name: Hacer Lint en el Codigo
        run: npx eslint . -f compact

      - name: Test de Aplicacio
        run: npm test